version: '{branch}-{build}'
configuration: RelWithDebInfo
clone_folder: C:\Textractor

branches:
  only:
    - master

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x64
    platform: x64
    qtbin: msvc2017_64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    arch: x86
    platform: Win32
    qtbin: msvc2017

before_build:
  - git submodule update --init
  - cd C:\
  - mkdir %arch%
  - cd %arch%
  - cmake -G "Visual Studio 15 2017" -A %platform% -DQt5_DIR="C:\Qt\5.13.2\%qtbin%\lib\cmake\Qt5" -DCMAKE_BUILD_TYPE="RelWithDebInfo" -DVERSION="" ../Textractor

build:
  project: C:\%arch%\Textractor.sln
  parallel: false
  verbosity: normal

after_build:
  - 7z a Textractor-Alpha%APPVEYOR_BUILD_NUMBER%-%arch%.zip C:\Textractor\builds\RelWithDebInfo_%arch%\*
  - appveyor PushArtifact Textractor-Alpha%APPVEYOR_BUILD_NUMBER%-%arch%.zip
